import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router";
import { Download, FileJson, FileText } from "lucide-react";

import { listFindings } from "@/api/findingsApi";
import { queryKeys } from "@/api/queryKeys";
import { getReport } from "@/api/reportsApi";
import { getScan } from "@/api/scansApi";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { InlineNotice } from "@/components/ui/InlineNotice";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Panel, PanelBody, PanelHeader } from "@/components/ui/Panel";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { SeverityBadge } from "@/components/ui/SeverityBadge";
import { SeverityDistribution } from "@/features/dashboard/SeverityDistribution";
import { ScanTabs } from "@/features/scans/ScanTabs";
import { formatDateTime } from "@/utils/format";

export function ReportPage() {
  const { scanId = "" } = useParams();

  const scanQuery = useQuery({
    queryKey: queryKeys.scan(scanId),
    queryFn: () => getScan(scanId),
    enabled: scanId.length > 0,
  });

  const reportQuery = useQuery({
    queryKey: queryKeys.report(scanId),
    queryFn: () => getReport(scanId),
    enabled: scanId.length > 0,
  });

  const findingsQuery = useQuery({
    queryKey: queryKeys.findings(scanId),
    queryFn: () => listFindings(scanId),
    enabled: scanId.length > 0,
  });

  const report = reportQuery.data;
  const findings = findingsQuery.data ?? [];

  const prioritized = (report?.prioritizedFindingIds ?? [])
    .map((id) => findings.find((finding) => finding.id === id))
    .filter((finding): finding is NonNullable<typeof finding> => Boolean(finding));

  return (
    <>
      <PageHeader
        title="Assessment report"
        breadcrumbs={[
          { label: "Scans", to: "/scans" },
          {
            label: scanQuery.data?.target_name ?? "Assessment",
            to: `/scans/${scanId}`,
          },
          { label: "Report" },
        ]}
        actions={
          <>
            <Button
              icon={<FileText aria-hidden className="size-4" />}
              disabled
              title="PDF export is not implemented"
            >
              Export PDF
            </Button>
            <Button
              icon={<FileJson aria-hidden className="size-4" />}
              disabled
              title="JSON export is not implemented"
            >
              Export JSON
            </Button>
          </>
        }
      />

      <ScanTabs scanId={scanId} />

      <InlineNotice tone="uv" title="Reports are not generated by the backend yet" className="mb-4">
        The narrative below is fixture text written by hand for review. No
        report-generation endpoint exists, and export is not implemented.
      </InlineNotice>

      {reportQuery.isError ? (
        <ErrorState
          error={reportQuery.error}
          onRetry={() => {
            void reportQuery.refetch();
          }}
        />
      ) : reportQuery.isPending ? (
        <LoadingSkeleton rows={10} label="Loading report" />
      ) : !report ? (
        <Panel>
          <EmptyState
            icon={FileText}
            title="No report for this assessment"
            description="A report is produced once an assessment completes and its findings have been normalized."
            action={
              <Link
                to={`/scans/${scanId}`}
                className="inline-flex h-10 items-center rounded-[var(--radius-control)] border border-line-strong bg-elevated px-4 text-sm font-medium text-fg transition-colors hover:bg-raised"
              >
                Back to progress
              </Link>
            }
          />
        </Panel>
      ) : (
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="space-y-4 lg:col-span-2">
            <Panel>
              <PanelHeader
                title="Executive summary"
                description={`Generated ${formatDateTime(report.generatedAt)}`}
                actions={<SeverityBadge severity={report.overallRisk} />}
              />
              <PanelBody>
                <p className="text-[0.9375rem] leading-relaxed text-muted">
                  {report.executiveSummary}
                </p>
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader
                title="Prioritized findings"
                description="Ordered by the review effort they warrant, not by score alone"
              />
              <PanelBody>
                {prioritized.length === 0 ? (
                  <p className="text-[0.8125rem] text-muted">
                    No findings were prioritized for this report.
                  </p>
                ) : (
                  <ol className="space-y-3">
                    {prioritized.map((finding, index) => (
                      <li
                        key={finding.id}
                        className="flex gap-3 rounded-[var(--radius-control)] border border-line bg-ink p-3"
                      >
                        <span className="font-mono text-xs text-faint tabular-nums">
                          {String(index + 1).padStart(2, "0")}
                        </span>
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <SeverityBadge severity={finding.severity} size="sm" />
                            <span className="font-mono text-[0.6875rem] text-faint">
                              {finding.source}
                            </span>
                          </div>
                          <p className="mt-1.5 text-[0.875rem] font-medium text-fg">
                            {finding.title}
                          </p>
                          <p className="mt-1 text-[0.8125rem] leading-relaxed text-muted">
                            {finding.impact}
                          </p>
                          <Link
                            to={`/scans/${scanId}/findings`}
                            className="mt-2 inline-block rounded-sm text-xs text-uv-glow underline underline-offset-2"
                          >
                            Open finding
                          </Link>
                        </div>
                      </li>
                    ))}
                  </ol>
                )}
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader title="Methodology" />
              <PanelBody>
                <ol className="space-y-2.5">
                  {report.methodology.map((step, index) => (
                    <li key={index} className="flex gap-3 text-[0.875rem] leading-relaxed">
                      <span className="mt-1.5 size-1 shrink-0 rounded-full bg-uv" aria-hidden />
                      <span className="text-muted">{step}</span>
                    </li>
                  ))}
                </ol>
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader
                title="Limitations"
                description="What this assessment did not cover"
              />
              <PanelBody>
                <ul className="space-y-2.5">
                  {report.limitations.map((limitation, index) => (
                    <li key={index} className="flex gap-3 text-[0.875rem] leading-relaxed">
                      <span
                        className="mt-1.5 size-1 shrink-0 rounded-full bg-line-strong"
                        aria-hidden
                      />
                      <span className="text-muted">{limitation}</span>
                    </li>
                  ))}
                </ul>
              </PanelBody>
            </Panel>
          </div>

          <div className="space-y-4">
            <Panel>
              <PanelHeader title="Severity counts" />
              <PanelBody>
                <SeverityDistribution counts={report.severityCounts} />
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader title="Scope" />
              <PanelBody className="space-y-4">
                <div>
                  <SectionLabel className="mb-2">In scope</SectionLabel>
                  <ul className="space-y-1">
                    {report.scope.inScope.map((asset) => (
                      <li key={asset} className="font-mono text-xs break-all text-fg">
                        {asset}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <SectionLabel className="mb-2">Out of scope</SectionLabel>
                  <ul className="space-y-1">
                    {report.scope.outOfScope.map((asset) => (
                      <li key={asset} className="font-mono text-xs break-all text-faint">
                        {asset}
                      </li>
                    ))}
                  </ul>
                </div>
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader title="Authorization statement" />
              <PanelBody className="space-y-3">
                <p className="text-[0.8125rem] leading-relaxed text-muted">
                  {report.authorizationStatement}
                </p>
                <dl className="space-y-2 border-t border-line pt-3 text-[0.8125rem]">
                  <div className="flex items-baseline justify-between gap-3">
                    <dt className="text-muted">Method</dt>
                    <dd className="text-fg">{report.scope.authorizationMethod}</dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-3">
                    <dt className="text-muted">Decided</dt>
                    <dd className="font-mono text-xs text-fg">
                      {formatDateTime(report.scope.authorizationDecidedAt)}
                    </dd>
                  </div>
                </dl>
              </PanelBody>
            </Panel>

            <Panel>
              <PanelHeader title="Export" />
              <PanelBody className="space-y-3">
                <p className="text-[0.8125rem] leading-relaxed text-muted">
                  Export produces a signed, self-contained copy of this report
                  for sharing with a development team or a bounty program.
                </p>
                <div className="flex flex-wrap gap-2">
                  <Button
                    size="sm"
                    icon={<Download aria-hidden className="size-3.5" />}
                    disabled
                  >
                    PDF
                  </Button>
                  <Button
                    size="sm"
                    icon={<Download aria-hidden className="size-3.5" />}
                    disabled
                  >
                    JSON
                  </Button>
                </div>
                <p className="font-mono text-[0.6875rem] text-faint">
                  Both formats: not implemented
                </p>
              </PanelBody>
            </Panel>
          </div>
        </div>
      )}
    </>
  );
}
